## Import Libraries

In [1]:
import pandas as pd

Data has already been merged (see 'data story so far.docx'). Read CSV and see dataframe.

In [2]:
data = pd.read_csv("reduced_2019.csv")

data_df = data

data_df.head()

,Crime ID,Crime type,Last outcome category,Month,Longitude,Latitude,Location,LSOA code,LSOA name,District code (2019),District name (2019),Description,Population,Index of Multiple Deprivation (IMD),Income deprivation- Average score,Income deprivation - Rank of average score,Income - Rank of proportion of LSOAs in most deprived 10% nationally
0,b0854078f33cc4e2ecd7353c40d3a03120063e7d39134b...,Burglary,Investigation complete; no suspect identified,2019-01,-1.850519,52.589275,On or near Crown Lane,E01009417,Birmingham 001A,E08000025,Birmingham,Urban with Major Conurbation,1073045.0,7,0.222,7,5
1,b48f19d1ca24bd7e1ef53952c1472314c1af57240df6d5...,Other theft,Investigation complete; no suspect identified,2019-01,-1.850056,52.591108,On or near Walsall Road,E01009417,Birmingham 001A,E08000025,Birmingham,Urban with Major Conurbation,1073045.0,7,0.222,7,5
2,2ea61ee241faeac03c5595efc0e3d838d79f20f5831f24...,Public order,Investigation complete; no suspect identified,2019-01,-1.850772,52.588691,On or near Seymour Gardens,E01009417,Birmingham 001A,E08000025,Birmingham,Urban with Major Conurbation,1073045.0,7,0.222,7,5
3,0fd56c14bbd052c45e7e9abc1c182c5201e5664a61dc03...,Criminal damage and arson,Investigation complete; no suspect identified,2019-02,-1.850772,52.588691,On or near Seymour Gardens,E01009417,Birmingham 001A,E08000025,Birmingham,Urban with Major Conurbation,1073045.0,7,0.222,7,5
4,cadab8dbc07947f5db64c9c0206077758cbbad346611cc...,Criminal damage and arson,Investigation complete; no suspect identified,2019-02,-1.850772,52.588691,On or near Seymour Gardens,E01009417,Birmingham 001A,E08000025,Birmingham,Urban with Major Conurbation,1073045.0,7,0.222,7,5

## Cleaning data

Viewing shape and contents of data.

In [3]:
data_df.shape

(296032, 17)

In [4]:
data_df.columns

Index(['Crime ID', 'Crime type', 'Last outcome category', 'Month', 'Longitude',
       'Latitude', 'Location', 'LSOA code', 'LSOA name',
       'District code (2019)', 'District name (2019)', 'Description',
       'Population', 'Index of Multiple Deprivation (IMD)',
       'Income deprivation- Average score ',
       'Income deprivation - Rank of average score ',
       'Income - Rank of proportion of LSOAs in most deprived 10% nationally '],
      dtype='object')

In [5]:
data_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 296032 entries, 0 to 296031
Data columns (total 17 columns):
 #   Column                                                                 Non-Null Count   Dtype
---  ------                                                                 --------------   -----
 0   Crime ID                                                               259543 non-null  object
 1   Crime type                                                             296032 non-null  object
 2   Last outcome category                                                  259543 non-null  object
 3   Month                                                                  296032 non-null  object
 4   Longitude                                                              296032 non-null  float64
 5   Latitude                                                               296032 non-null  float64
 6   Location                                                               296032 non-null  object
 7   LSOA code                                                              296032 non-null  object
 8   LSOA name                                                              296032 non-null  object
 9   District code (2019)                                                   296032 non-null  object
 10  District name (2019)                                                   296032 non-null  object
 11  Description                                                            296032 non-null  object
 12  Population                                                             296032 non-null  float64
 13  Index of Multiple Deprivation (IMD)                                    296032 non-null  int64
 14  Income deprivation- Average score                                      296032 non-null  float64
 15  Income deprivation - Rank of average score                             296032 non-null  int64
 16  Income - Rank of proportion of LSOAs in most deprived 10% nationally   296032 non-null  int64
dtypes: float64(4), int64(3), object(10)
memory usage: 38.4+ MB

In [6]:
data_df.duplicated()
boolean_series_of_duplicates = data_df.duplicated()
len(data_df.loc[boolean_series_of_duplicates, :])

8649

In [7]:
data_df.loc[boolean_series_of_duplicates, :]

,Crime ID,Crime type,Last outcome category,Month,Longitude,Latitude,Location,LSOA code,LSOA name,District code (2019),District name (2019),Description,Population,Index of Multiple Deprivation (IMD),Income deprivation- Average score,Income deprivation - Rank of average score,Income - Rank of proportion of LSOAs in most deprived 10% nationally
67,NaN,Anti-social behaviour,NaN,2019-07,-1.840641,52.598270,On or near Badgers Bank Road,E01009418,Birmingham 001B,E08000025,Birmingham,Urban with Major Conurbation,1073045.0,5,0.222,7,5
68,NaN,Anti-social behaviour,NaN,2019-07,-1.845780,52.593827,On or near Hook Drive,E01009418,Birmingham 001B,E08000025,Birmingham,Urban with Major Conurbation,1073045.0,5,0.222,7,5
159,NaN,Anti-social behaviour,NaN,2019-12,-1.849079,52.595980,On or near Blackberry Lane,E01009419,Birmingham 001C,E08000025,Birmingham,Urban with Major Conurbation,1073045.0,6,0.222,7,5
160,NaN,Anti-social behaviour,NaN,2019-12,-1.849079,52.595980,On or near Blackberry Lane,E01009419,Birmingham 001C,E08000025,Birmingham,Urban with Major Conurbation,1073045.0,6,0.222,7,5
199,NaN,Anti-social behaviour,NaN,2019-07,-1.843092,52.602471,On or near Moore Close,E01009433,Birmingham 001D,E08000025,Birmingham,Urban with Major Conurbation,1073045.0,9,0.222,7,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
295786,NaN,Anti-social behaviour,NaN,2019-02,-2.156332,52.610149,On or near Green Lane,E01010545,Wolverhampton 009E,E08000031,Wolverhampton,Urban with Major Conurbation,249470.0,7,0.211,11,14
295788,NaN,Anti-social behaviour,NaN,2019-02,-2.150734,52.605472,On or near Sports/Recreation Area,E01010545,Wolverhampton 009E,E08000031,Wolverhampton,Urban with Major Conurbation,249470.0,7,0.211,11,14
295789,NaN,Anti-social behaviour,NaN,2019-02,-2.150734,52.605472,On or near Sports/Recreation Area,E01010545,Wolverhampton 009E,E08000031,Wolverhampton,Urban with Major Conurbation,249470.0,7,0.211,11,14
295818,NaN,Anti-social behaviour,NaN,2019-06,-2.156332,52.610149,On or near Green Lane,E01010545,Wolverhampton 009E,E08000031,Wolverhampton,Urban with Major Conurbation,249470.0,7,0.211,11,14
295863,NaN,Anti-social behaviour,NaN,2019-12,-2.151333,52.607854,On or near Kestrel Rise,E01010545,Wolverhampton 009E,E08000031,Wolverhampton,Urban with Major Conurbation,249470.0,7,0.211,11,14

We investigated the duplicates and found that the abive number was the number of crime IDs that had null values in similar locations. They also tended to fall into the crime type of anti-social behaviour.

In [8]:
data_df.isnull().sum()

Crime ID                                                                 36489
Crime type                                                                   0
Last outcome category                                                    36489
Month                                                                        0
Longitude                                                                    0
Latitude                                                                     0
Location                                                                     0
LSOA code                                                                    0
LSOA name                                                                    0
District code (2019)                                                         0
District name (2019)                                                         0
Description                                                                  0
Population                                                                   0
Index of Multiple Deprivation (IMD)                                          0
Income deprivation- Average score                                            0
Income deprivation - Rank of average score                                   0
Income - Rank of proportion of LSOAs in most deprived 10% nationally         0
dtype: int64

The last outcome column shows many null values, we have decided to change this to 'No outcome recorded' rather than leave it blank.

In [9]:
# Fill in missing values in 'last outcome category'
data_df["Last outcome category"] = data_df["Last outcome category"].fillna('No outcome recorded')

## Filter West Midlands data

We only want the data for the follwing districts: Birmingham, Coventry, Dudley, Sandwell, Solihull, Walsall, Wolverhampton. We will then filter this data into a new West_Midlands_df

In [13]:
West_midlands_df = data_df[(data_df["District name (2019)"]=="Birmingham")|(data_df["District name (2019)"]=="Coventry")|(data_df["District name (2019)"]=="Dudley")|(data_df["District name (2019)"]=="Sandwell")|(data_df["District name (2019)"]=="Solihull")|(data_df["District name (2019)"]=="Walsall")|(data_df["District name (2019)"]=="Wolverhampton")]

West_midlands_df.head()

,Crime ID,Crime type,Last outcome category,Month,Longitude,Latitude,Location,LSOA code,LSOA name,District code (2019),District name (2019),Description,Population,Index of Multiple Deprivation (IMD),Income deprivation- Average score,Income deprivation - Rank of average score,Income - Rank of proportion of LSOAs in most deprived 10% nationally
0,b0854078f33cc4e2ecd7353c40d3a03120063e7d39134b...,Burglary,Investigation complete; no suspect identified,2019-01,-1.850519,52.589275,On or near Crown Lane,E01009417,Birmingham 001A,E08000025,Birmingham,Urban with Major Conurbation,1073045.0,7,0.222,7,5
1,b48f19d1ca24bd7e1ef53952c1472314c1af57240df6d5...,Other theft,Investigation complete; no suspect identified,2019-01,-1.850056,52.591108,On or near Walsall Road,E01009417,Birmingham 001A,E08000025,Birmingham,Urban with Major Conurbation,1073045.0,7,0.222,7,5
2,2ea61ee241faeac03c5595efc0e3d838d79f20f5831f24...,Public order,Investigation complete; no suspect identified,2019-01,-1.850772,52.588691,On or near Seymour Gardens,E01009417,Birmingham 001A,E08000025,Birmingham,Urban with Major Conurbation,1073045.0,7,0.222,7,5
3,0fd56c14bbd052c45e7e9abc1c182c5201e5664a61dc03...,Criminal damage and arson,Investigation complete; no suspect identified,2019-02,-1.850772,52.588691,On or near Seymour Gardens,E01009417,Birmingham 001A,E08000025,Birmingham,Urban with Major Conurbation,1073045.0,7,0.222,7,5
4,cadab8dbc07947f5db64c9c0206077758cbbad346611cc...,Criminal damage and arson,Investigation complete; no suspect identified,2019-02,-1.850772,52.588691,On or near Seymour Gardens,E01009417,Birmingham 001A,E08000025,Birmingham,Urban with Major Conurbation,1073045.0,7,0.222,7,5

In [18]:
West_midlands_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 295541 entries, 0 to 295871
Data columns (total 17 columns):
 #   Column                                                                 Non-Null Count   Dtype
---  ------                                                                 --------------   -----
 0   Crime ID                                                               259087 non-null  object
 1   Crime type                                                             295541 non-null  object
 2   Last outcome category                                                  295541 non-null  object
 3   Month                                                                  295541 non-null  object
 4   Longitude                                                              295541 non-null  float64
 5   Latitude                                                               295541 non-null  float64
 6   Location                                                               295541 non-null  object
 7   LSOA code                                                              295541 non-null  object
 8   LSOA name                                                              295541 non-null  object
 9   District code (2019)                                                   295541 non-null  object
 10  District name (2019)                                                   295541 non-null  object
 11  Description                                                            295541 non-null  object
 12  Population                                                             295541 non-null  float64
 13  Index of Multiple Deprivation (IMD)                                    295541 non-null  int64
 14  Income deprivation- Average score                                      295541 non-null  float64
 15  Income deprivation - Rank of average score                             295541 non-null  int64
 16  Income - Rank of proportion of LSOAs in most deprived 10% nationally   295541 non-null  int64
dtypes: float64(4), int64(3), object(10)
memory usage: 40.6+ MB

In [20]:
# Fill in missing values in 'Crime ID'
West_midlands_df["Crime ID"] = West_midlands_df["Crime ID"].fillna('No ID recorded')

C:\Users\gcwhi\AppData\Local\Temp/ipykernel_27628/3972491802.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  West_midlands_df["Crime ID"] = West_midlands_df["Crime ID"].fillna('No ID recorded')

In [21]:
West_midlands_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 295541 entries, 0 to 295871
Data columns (total 17 columns):
 #   Column                                                                 Non-Null Count   Dtype
---  ------                                                                 --------------   -----
 0   Crime ID                                                               295541 non-null  object
 1   Crime type                                                             295541 non-null  object
 2   Last outcome category                                                  295541 non-null  object
 3   Month                                                                  295541 non-null  object
 4   Longitude                                                              295541 non-null  float64
 5   Latitude                                                               295541 non-null  float64
 6   Location                                                               295541 non-null  object
 7   LSOA code                                                              295541 non-null  object
 8   LSOA name                                                              295541 non-null  object
 9   District code (2019)                                                   295541 non-null  object
 10  District name (2019)                                                   295541 non-null  object
 11  Description                                                            295541 non-null  object
 12  Population                                                             295541 non-null  float64
 13  Index of Multiple Deprivation (IMD)                                    295541 non-null  int64
 14  Income deprivation- Average score                                      295541 non-null  float64
 15  Income deprivation - Rank of average score                             295541 non-null  int64
 16  Income - Rank of proportion of LSOAs in most deprived 10% nationally   295541 non-null  int64
dtypes: float64(4), int64(3), object(10)
memory usage: 40.6+ MB

In [22]:
West_midlands_df.head()

,Crime ID,Crime type,Last outcome category,Month,Longitude,Latitude,Location,LSOA code,LSOA name,District code (2019),District name (2019),Description,Population,Index of Multiple Deprivation (IMD),Income deprivation- Average score,Income deprivation - Rank of average score,Income - Rank of proportion of LSOAs in most deprived 10% nationally
0,b0854078f33cc4e2ecd7353c40d3a03120063e7d39134b...,Burglary,Investigation complete; no suspect identified,2019-01,-1.850519,52.589275,On or near Crown Lane,E01009417,Birmingham 001A,E08000025,Birmingham,Urban with Major Conurbation,1073045.0,7,0.222,7,5
1,b48f19d1ca24bd7e1ef53952c1472314c1af57240df6d5...,Other theft,Investigation complete; no suspect identified,2019-01,-1.850056,52.591108,On or near Walsall Road,E01009417,Birmingham 001A,E08000025,Birmingham,Urban with Major Conurbation,1073045.0,7,0.222,7,5
2,2ea61ee241faeac03c5595efc0e3d838d79f20f5831f24...,Public order,Investigation complete; no suspect identified,2019-01,-1.850772,52.588691,On or near Seymour Gardens,E01009417,Birmingham 001A,E08000025,Birmingham,Urban with Major Conurbation,1073045.0,7,0.222,7,5
3,0fd56c14bbd052c45e7e9abc1c182c5201e5664a61dc03...,Criminal damage and arson,Investigation complete; no suspect identified,2019-02,-1.850772,52.588691,On or near Seymour Gardens,E01009417,Birmingham 001A,E08000025,Birmingham,Urban with Major Conurbation,1073045.0,7,0.222,7,5
4,cadab8dbc07947f5db64c9c0206077758cbbad346611cc...,Criminal damage and arson,Investigation complete; no suspect identified,2019-02,-1.850772,52.588691,On or near Seymour Gardens,E01009417,Birmingham 001A,E08000025,Birmingham,Urban with Major Conurbation,1073045.0,7,0.222,7,5

In [23]:
West_midlands_df.to_csv('clean_2019.csv', index=False)

In [26]:
lidd = pd.read_excel("localincomedeprivationdata.xlsx", engine='openpyxl')

In [27]:
lidd.head()

,LSOA code (2011),LSOA name (2011),Local Authority District code (2019),Local Authority District name (2019),Overall Index of Multiple Deprivation (IMD) Score,Index of Multiple Deprivation (IMD) Rank (where 1 is most deprived),Index of Multiple Deprivation (IMD) Decile (where 1 is most deprived 10% of LSOAs),Income Score (rate),Income Rank (where 1 is most deprived),Income Decile (where 1 is most deprived 10% of LSOAs),Total population: mid 2015 (excluding prisoners),Dependent Children aged 0-15: mid 2015 (excluding prisoners),Population aged 16-59: mid 2015 (excluding prisoners),Older population aged 60 and over: mid 2015 (excluding prisoners),Working age population 18-59/64: for use with Employment Deprivation Domain (excluding prisoners)
0,E01031338,Adur 002A,E07000223,Adur,5.518,30006,10,0.054,25262,8,1159,202,603,354,618
1,E01031339,Adur 002B,E07000223,Adur,6.186,29228,9,0.052,25709,8,1200,229,653,318,664
2,E01031340,Adur 002C,E07000223,Adur,5.213,30309,10,0.027,31386,10,1464,241,691,532,707
3,E01031341,Adur 008A,E07000223,Adur,38.777,4639,2,0.237,4645,2,1371,239,775,357,785
4,E01031342,Adur 008B,E07000223,Adur,16.050,17896,6,0.083,19015,6,1731,235,760,736,768

In [28]:
lidd = lidd.rename(columns={"Overall Index of Multiple Deprivation (IMD) Score":"LSOA IMD Score"})

In [29]:
lidd.head()

,LSOA code (2011),LSOA name (2011),Local Authority District code (2019),Local Authority District name (2019),LSOA IMD Score,Index of Multiple Deprivation (IMD) Rank (where 1 is most deprived),Index of Multiple Deprivation (IMD) Decile (where 1 is most deprived 10% of LSOAs),Income Score (rate),Income Rank (where 1 is most deprived),Income Decile (where 1 is most deprived 10% of LSOAs),Total population: mid 2015 (excluding prisoners),Dependent Children aged 0-15: mid 2015 (excluding prisoners),Population aged 16-59: mid 2015 (excluding prisoners),Older population aged 60 and over: mid 2015 (excluding prisoners),Working age population 18-59/64: for use with Employment Deprivation Domain (excluding prisoners)
0,E01031338,Adur 002A,E07000223,Adur,5.518,30006,10,0.054,25262,8,1159,202,603,354,618
1,E01031339,Adur 002B,E07000223,Adur,6.186,29228,9,0.052,25709,8,1200,229,653,318,664
2,E01031340,Adur 002C,E07000223,Adur,5.213,30309,10,0.027,31386,10,1464,241,691,532,707
3,E01031341,Adur 008A,E07000223,Adur,38.777,4639,2,0.237,4645,2,1371,239,775,357,785
4,E01031342,Adur 008B,E07000223,Adur,16.050,17896,6,0.083,19015,6,1731,235,760,736,768

In [30]:
lidd = lidd.rename(columns={"Index of Multiple Deprivation (IMD) Rank (where 1 is most deprived)":"LSOA IMD Rank"})

In [31]:
lidd.head()

,LSOA code (2011),LSOA name (2011),Local Authority District code (2019),Local Authority District name (2019),LSOA IMD Score,LSOA IMD Rank,Index of Multiple Deprivation (IMD) Decile (where 1 is most deprived 10% of LSOAs),Income Score (rate),Income Rank (where 1 is most deprived),Income Decile (where 1 is most deprived 10% of LSOAs),Total population: mid 2015 (excluding prisoners),Dependent Children aged 0-15: mid 2015 (excluding prisoners),Population aged 16-59: mid 2015 (excluding prisoners),Older population aged 60 and over: mid 2015 (excluding prisoners),Working age population 18-59/64: for use with Employment Deprivation Domain (excluding prisoners)
0,E01031338,Adur 002A,E07000223,Adur,5.518,30006,10,0.054,25262,8,1159,202,603,354,618
1,E01031339,Adur 002B,E07000223,Adur,6.186,29228,9,0.052,25709,8,1200,229,653,318,664
2,E01031340,Adur 002C,E07000223,Adur,5.213,30309,10,0.027,31386,10,1464,241,691,532,707
3,E01031341,Adur 008A,E07000223,Adur,38.777,4639,2,0.237,4645,2,1371,239,775,357,785
4,E01031342,Adur 008B,E07000223,Adur,16.050,17896,6,0.083,19015,6,1731,235,760,736,768

In [32]:
lidd = lidd.rename(columns={"Income Rank (where 1 is most deprived)":"LSOA Income Rank"})

In [33]:
lidd.head()

,LSOA code (2011),LSOA name (2011),Local Authority District code (2019),Local Authority District name (2019),LSOA IMD Score,LSOA IMD Rank,Index of Multiple Deprivation (IMD) Decile (where 1 is most deprived 10% of LSOAs),Income Score (rate),LSOA Income Rank,Income Decile (where 1 is most deprived 10% of LSOAs),Total population: mid 2015 (excluding prisoners),Dependent Children aged 0-15: mid 2015 (excluding prisoners),Population aged 16-59: mid 2015 (excluding prisoners),Older population aged 60 and over: mid 2015 (excluding prisoners),Working age population 18-59/64: for use with Employment Deprivation Domain (excluding prisoners)
0,E01031338,Adur 002A,E07000223,Adur,5.518,30006,10,0.054,25262,8,1159,202,603,354,618
1,E01031339,Adur 002B,E07000223,Adur,6.186,29228,9,0.052,25709,8,1200,229,653,318,664
2,E01031340,Adur 002C,E07000223,Adur,5.213,30309,10,0.027,31386,10,1464,241,691,532,707
3,E01031341,Adur 008A,E07000223,Adur,38.777,4639,2,0.237,4645,2,1371,239,775,357,785
4,E01031342,Adur 008B,E07000223,Adur,16.050,17896,6,0.083,19015,6,1731,235,760,736,768

In [35]:
del lidd['LSOA name (2011)']
del lidd['Local Authority District code (2019)']
del lidd['Local Authority District name (2019)']
del lidd['Index of Multiple Deprivation (IMD) Decile (where 1 is most deprived 10% of LSOAs)']
del lidd['Income Score (rate)']
del lidd['Income Decile (where 1 is most deprived 10% of LSOAs)']
del lidd['Total population: mid 2015 (excluding prisoners)']
del lidd['Dependent Children aged 0-15: mid 2015 (excluding prisoners)']
del lidd['Population aged 16-59: mid 2015 (excluding prisoners)']
del lidd['Older population aged 60 and over: mid 2015 (excluding prisoners)']
del lidd['Working age population 18-59/64: for use with Employment Deprivation Domain (excluding prisoners) ']

In [36]:
lidd.head()

  LSOA code (2011)  LSOA IMD Score  LSOA IMD Rank  LSOA Income Rank
0        E01031338           5.518          30006             25262
1        E01031339           6.186          29228             25709
2        E01031340           5.213          30309             31386
3        E01031341          38.777           4639              4645
4        E01031342          16.050          17896             19015

In [40]:
lidd = lidd.rename(columns={"Local Authority District code (2019)":"LSOA code"})
lidd.head()

   LSOA code  LSOA IMD Score  LSOA IMD Rank  LSOA Income Rank
0  E01031338           5.518          30006             25262
1  E01031339           6.186          29228             25709
2  E01031340           5.213          30309             31386
3  E01031341          38.777           4639              4645
4  E01031342          16.050          17896             19015

In [41]:
West_midlands_df1 = pd.merge(West_midlands_df, lidd, on = "LSOA code")
West_midlands_df1.head()

,Crime ID,Crime type,Last outcome category,Month,Longitude,Latitude,Location,LSOA code,LSOA name,District code (2019),District name (2019),Description,Population,Index of Multiple Deprivation (IMD),Income deprivation- Average score,Income deprivation - Rank of average score,Income - Rank of proportion of LSOAs in most deprived 10% nationally,LSOA IMD Score,LSOA IMD Rank,LSOA Income Rank
0,b0854078f33cc4e2ecd7353c40d3a03120063e7d39134b...,Burglary,Investigation complete; no suspect identified,2019-01,-1.850519,52.589275,On or near Crown Lane,E01009417,Birmingham 001A,E08000025,Birmingham,Urban with Major Conurbation,1073045.0,7,0.222,7,5,12.652,21433,18278
1,b48f19d1ca24bd7e1ef53952c1472314c1af57240df6d5...,Other theft,Investigation complete; no suspect identified,2019-01,-1.850056,52.591108,On or near Walsall Road,E01009417,Birmingham 001A,E08000025,Birmingham,Urban with Major Conurbation,1073045.0,7,0.222,7,5,12.652,21433,18278
2,2ea61ee241faeac03c5595efc0e3d838d79f20f5831f24...,Public order,Investigation complete; no suspect identified,2019-01,-1.850772,52.588691,On or near Seymour Gardens,E01009417,Birmingham 001A,E08000025,Birmingham,Urban with Major Conurbation,1073045.0,7,0.222,7,5,12.652,21433,18278
3,0fd56c14bbd052c45e7e9abc1c182c5201e5664a61dc03...,Criminal damage and arson,Investigation complete; no suspect identified,2019-02,-1.850772,52.588691,On or near Seymour Gardens,E01009417,Birmingham 001A,E08000025,Birmingham,Urban with Major Conurbation,1073045.0,7,0.222,7,5,12.652,21433,18278
4,cadab8dbc07947f5db64c9c0206077758cbbad346611cc...,Criminal damage and arson,Investigation complete; no suspect identified,2019-02,-1.850772,52.588691,On or near Seymour Gardens,E01009417,Birmingham 001A,E08000025,Birmingham,Urban with Major Conurbation,1073045.0,7,0.222,7,5,12.652,21433,18278

In [42]:
West_midlands_df1.columns

Index(['Crime ID', 'Crime type', 'Last outcome category', 'Month', 'Longitude',
       'Latitude', 'Location', 'LSOA code', 'LSOA name',
       'District code (2019)', 'District name (2019)', 'Description',
       'Population', 'Index of Multiple Deprivation (IMD)',
       'Income deprivation- Average score ',
       'Income deprivation - Rank of average score ',
       'Income - Rank of proportion of LSOAs in most deprived 10% nationally ',
       'LSOA IMD Score', 'LSOA IMD Rank', 'LSOA Income Rank'],
      dtype='object')

In [43]:
West_midlands_df1 = West_midlands_df1.reindex(['Crime ID', 'Crime type', 'Last outcome category', 'Month', 'Longitude',
       'Latitude', 'Location', 'LSOA code', 'LSOA name','LSOA IMD Score', 'LSOA IMD Rank', 'LSOA Income Rank',
       'District code (2019)', 'District name (2019)', 'Description',
       'Population', 'Index of Multiple Deprivation (IMD)',
       'Income deprivation- Average score ',
       'Income deprivation - Rank of average score ',
       'Income - Rank of proportion of LSOAs in most deprived 10% nationally '
       ], axis=1)

In [44]:
West_midlands_df1.head()

,Crime ID,Crime type,Last outcome category,Month,Longitude,Latitude,Location,LSOA code,LSOA name,LSOA IMD Score,LSOA IMD Rank,LSOA Income Rank,District code (2019),District name (2019),Description,Population,Index of Multiple Deprivation (IMD),Income deprivation- Average score,Income deprivation - Rank of average score,Income - Rank of proportion of LSOAs in most deprived 10% nationally
0,b0854078f33cc4e2ecd7353c40d3a03120063e7d39134b...,Burglary,Investigation complete; no suspect identified,2019-01,-1.850519,52.589275,On or near Crown Lane,E01009417,Birmingham 001A,12.652,21433,18278,E08000025,Birmingham,Urban with Major Conurbation,1073045.0,7,0.222,7,5
1,b48f19d1ca24bd7e1ef53952c1472314c1af57240df6d5...,Other theft,Investigation complete; no suspect identified,2019-01,-1.850056,52.591108,On or near Walsall Road,E01009417,Birmingham 001A,12.652,21433,18278,E08000025,Birmingham,Urban with Major Conurbation,1073045.0,7,0.222,7,5
2,2ea61ee241faeac03c5595efc0e3d838d79f20f5831f24...,Public order,Investigation complete; no suspect identified,2019-01,-1.850772,52.588691,On or near Seymour Gardens,E01009417,Birmingham 001A,12.652,21433,18278,E08000025,Birmingham,Urban with Major Conurbation,1073045.0,7,0.222,7,5
3,0fd56c14bbd052c45e7e9abc1c182c5201e5664a61dc03...,Criminal damage and arson,Investigation complete; no suspect identified,2019-02,-1.850772,52.588691,On or near Seymour Gardens,E01009417,Birmingham 001A,12.652,21433,18278,E08000025,Birmingham,Urban with Major Conurbation,1073045.0,7,0.222,7,5
4,cadab8dbc07947f5db64c9c0206077758cbbad346611cc...,Criminal damage and arson,Investigation complete; no suspect identified,2019-02,-1.850772,52.588691,On or near Seymour Gardens,E01009417,Birmingham 001A,12.652,21433,18278,E08000025,Birmingham,Urban with Major Conurbation,1073045.0,7,0.222,7,5

In [45]:
West_midlands_df1.to_csv('clean_2019_1.csv', index=False)